<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b73c5584-b3fd-4724-ad38-3b06532c1dd3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ComplianceTracker.Application\ComplianceTracker.Application.csproj" />
    <ProjectReference Include="..\ComplianceTracker.Domain\ComplianceTracker.Domain.csproj" />
    <ProjectReference Include="..\ComplianceTracker.Infrastructure\ComplianceTracker.Infrastructure.csproj" />
  </ItemGroup>

</Project>
